# Generated by Django 2.1.5 on 2019-03-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.IntegerField()),
                ('process_id', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('property', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data.Property')),
            ],
        ),
        migrations.CreateModel(
            name='VisibilityRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('public', 'Publico'), ('onlyme', 'Solo yo'), ('contacts', 'Solo mis contactos'), ('service', 'Para un servicio'), ('custom-list-customers', ' Lista de Clientes'), ('custom-list-providers', ' Lista de Proveedores')], default='onlyme', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('abstraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privacy.Abstraction')),
            ],
        ),
    ]
