# Generated by Django 2.1.5 on 2019-03-08 21:25

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('provider', '0001_initial'),
        ('data', '0002_property_visibility_set'),
        ('customer', '0003_auto_20190307_1623'),
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisibilityRule',
            new_name='Visibility',
        ),
    ]
