# Generated by Django 2.1.5 on 2019-03-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190307_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='providers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Provider'),
        ),
    ]
