# Generated by Django 2.1.7 on 2019-03-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0004_auto_20190308_2140'),
        ('customer', '0003_auto_20190307_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='visibility',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='visibility',
            field=models.ManyToManyField(blank=True, to='privacy.Visibility'),
        ),
    ]
