# Generated by Django 2.1.7 on 2019-03-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20190321_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_data', to='customer.Customer'),
        ),
    ]
