# Generated by Django 2.1.7 on 2019-04-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequest', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='request',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='serviceRequest.Request'),
            preserve_default=False,
        ),
    ]
