# Generated by Django 2.1.5 on 2019-03-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='visibility_set',
            field=models.ManyToManyField(blank=True, to='privacy.VisibilityRule'),
        ),
    ]
