# Generated by Django 2.1.5 on 2019-02-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20190210_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='descripcion',
            new_name='description',
        ),
    ]
