# Generated by Django 2.1.5 on 2019-02-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20190213_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='control_type',
            field=models.CharField(default='input-text', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='customers',
            field=models.ManyToManyField(blank=True, to='network.Customer'),
        ),
    ]
