# Generated by Django 2.1.5 on 2019-03-05 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20190228_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='control_type',
            field=models.CharField(choices=[('text-input', 'Entrada de texto'), ('date-input', 'Entrada de fecha'), ('paragraph-input', 'Entrada de texto multilinea'), ('image-input', 'Entrada de imagen')], max_length=200),
        ),
        migrations.AlterField(
            model_name='visibilityrule',
            name='abstraccion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='network.Abstraction'),
        ),
    ]
