# Generated by Django 2.1.5 on 2019-03-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20190305_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstraction',
            name='property',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='network.Property'),
        ),
        migrations.AlterField(
            model_name='visibilityrule',
            name='abstraccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Abstraction'),
        ),
    ]
