# Generated by Django 2.1.7 on 2019-04-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20190307_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
