# Generated by Django 2.1.5 on 2019-03-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSystemValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textual', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.ScoreSystem')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='scoreprovider',
            name='score_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.ScoreSystem'),
        ),
        migrations.AddField(
            model_name='scoreprovider',
            name='score_system_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.ScoreSystemValue'),
        ),
        migrations.AddField(
            model_name='scoreprovider',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.Skill'),
        ),
        migrations.AddField(
            model_name='scorecustomer',
            name='score_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.ScoreSystem'),
        ),
        migrations.AddField(
            model_name='scorecustomer',
            name='score_system_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.ScoreSystemValue'),
        ),
        migrations.AddField(
            model_name='scorecustomer',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.Skill'),
        ),
    ]
