# Generated by Django 2.1.7 on 2019-03-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20190314_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerdata',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_data', to='provider.Provider'),
        ),
        migrations.AlterField(
            model_name='providerdata',
            name='visibility',
            field=models.ManyToManyField(blank=True, to='privacy.Visibility'),
        ),
    ]
