# Generated by Django 2.1.7 on 2019-03-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20190320_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='color',
            field=models.CharField(default='#f0f0f0', max_length=200),
            preserve_default=False,
        ),
    ]
