# Generated by Django 2.1.7 on 2019-04-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='provider.Provider'),
            preserve_default=False,
        ),
    ]
